/**
 * Upload keys are generated by the server and carry the owner and the image
 * size, so that attaching an upload needs no extra lookup and cannot target
 * another user's file:  users/<userId>/photos/<uuid>_<width>x<height>.jpg
 */
const PATTERN =
  /^users\/([^/]+)\/photos\/[0-9a-f-]{36}_(\d{1,5})x(\d{1,5})\.jpg$/;

/** Every file of a user lives under this prefix (account deletion). */
export function userStoragePrefix(userId: string): string {
  return `users/${userId}/`;
}

export function buildUploadKey(
  userId: string,
  id: string,
  size: { width: number; height: number },
): string {
  return `${userStoragePrefix(userId)}photos/${id}_${size.width}x${size.height}.jpg`;
}

/** Returns null when the key is malformed or belongs to another user. */
export function parseUploadKey(
  key: string,
  userId: string,
): { width: number; height: number } | null {
  const match = PATTERN.exec(key);
  if (!match || match[1] !== userId) return null;
  return { width: Number(match[2]), height: Number(match[3]) };
}
